;;; naga-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from naga-base.el

(register-definition-prefixes "naga-base" '("naga-"))


;;; Generated autoloads from naga-dimmed-theme.el

(when (and load-file-name (boundp 'custom-theme-load-path)) (let ((dir (file-name-as-directory (file-name-directory load-file-name)))) (add-to-list 'custom-theme-load-path dir) (unless (featurep 'naga-base) (load-file (expand-file-name "naga-base.el" dir)))))
(register-definition-prefixes "naga-dimmed-theme" '("naga-dimmed"))


;;; Generated autoloads from naga-theme.el

(when (and load-file-name (boundp 'custom-theme-load-path)) (let ((dir (file-name-as-directory (file-name-directory load-file-name)))) (add-to-list 'custom-theme-load-path dir) (unless (featurep 'naga-base) (load-file (expand-file-name "naga-base.el" dir)))))
(register-definition-prefixes "naga-theme" '("naga"))

;;; End of scraped data

(provide 'naga-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; naga-theme-autoloads.el ends here
